kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: cost-metrics-exporter
  namespace: costmanagement-metrics-operator
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'cost-metrics-exporter:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:12-ubi8'
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: 'https://github.com/mparram/cost-metrics-exporter.git'
      ref: main
    contextDir: /code/
  runPolicy: Serial