apiVersion: v1
kind: Service
metadata:
  name: cost-metrics-exporter
  namespace: costmanagement-metrics-operator
  labels:
    app: cost-metrics-exporter
spec:
  selector:
    app: cost-metrics-exporter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: 8080-tcp